name = "ITUPropagationModels"
uuid = "17778021-2b2c-4ecf-610a-391273688f7f"
authors = ["Alberto Mengali <disberd@gmail.com>", "Hillary Kchao <hillary.kchao@gmail.com>"]
repo = "https://github.com/JuliaSatcomFramework/ITUPropagationModels.jl"
version = "1.0.0-DEV"

[deps]
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
LiveServer = "16fef848-5104-11e9-1b77-fb7a48bbb589"

[weakdeps]
CoordRefSystems = "b46f11dc-f210-4604-bfba-323c1ec968cb"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[extensions]
CoordRefSystemsExt = "CoordRefSystems"
UnitfulExt = "Unitful"

[compat]
Artifacts = "1"
CoordRefSystems = "0.14 - 0.17"
LiveServer = "1.5.0"
Unitful = "1.23.0"
julia = "1.10"
